name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Use Node.js
      uses: actions/setup-node@v3.8.1
      with: 
        node-version: 20.6.1
    - name: Installing Firebase
      run: curl -sL https://firebase.tools | bash
    - name: Installing Dependencies
      run: npm install
    - name: Building React App
      run: npm run build
    - name: Deploying to Firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}